### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by YashAdhau9211** [HelloCigar/UP-Tap#1]
hey, I also want to make this project can you give the resources form where I can learn it form. thanks

**Comment by HelloCigar** [comment]
Hi. Please read our README, all the technologies we used are listed there with relevant links. This is currently work in progress. All the links have documentation for you to start learning. Feel free to clone our project, but we won't be accepting pull requests. Thanks. One tutorial that might help you grasp our tech stack: https://www.youtube.com/watch?v=JjBqRihjwKM.
